[package]
name = "tenex-gui"
version.workspace = true
edition.workspace = true

[[bin]]
name = "tenex-gui"
path = "src/main.rs"

[dependencies]
tenex-core = { path = "../tenex-core" }
anyhow.workspace = true
eframe.workspace = true
nostr-sdk.workspace = true
